### PR TITLE
Added buttonComponent Prop and possibility to use icon as buttonText

### PR DESCRIPTION
**Pull request by Linschlager**
Instead of using the hardcoded &lt;button&gt;, you can now define what to use as a button by passing the buttonComponent prop.
Also changed the propType of buttonText to allow for icons and such, not just plain strings

### CODE REVIEW

**Comment by HectorMu** [comment]
Hi, where i can configure the button component prop?

**Comment by Linschlager** [comment]
> HectorMu

There is a demo in the Readme.md

**Comment by sadaqabdo** [comment]
Hey @zsusac, would love this to get merged!

**Comment by Linschlager** [comment]
Closing this as it's clearly not maintained anymore

**Pull request closed without merging**
